// Define all available window and door types with their properties
export const windowTypes = [
  // Standard window types
  {
    id: "single",
    name: "Single Casement",
    description: "A single pane window that opens outward",
    minWidth: 400,
    maxWidth: 1000,
    minHeight: 500,
    maxHeight: 2000,
    category: "window",
  },
  {
    id: "double",
    name: "Double Casement",
    description: "A window with two panes side by side, both can open outward",
    minWidth: 800,
    maxWidth: 2000,
    minHeight: 500,
    maxHeight: 2000,
    category: "window",
  },
  {
    id: "triple",
    name: "Triple Casement",
    description: "A window with three panes side by side",
    minWidth: 1200,
    maxWidth: 2500,
    minHeight: 500,
    maxHeight: 2000,
    category: "window",
  },
  {
    id: "quad",
    name: "Quad Casement",
    description: "A window with four panes side by side",
    minWidth: 1600,
    maxWidth: 3000,
    minHeight: 500,
    maxHeight: 2000,
    category: "window",
  },
  
  // Transom window types
  {
    id: "single-transom",
    name: "Single with Transom",
    description: "A single casement window with a fixed rectangular transom at the top",
    minWidth: 400,
    maxWidth: 1000,
    minHeight: 800,
    maxHeight: 2000,
    category: "window",
  },
  {
    id: "double-transom",
    name: "Double with Transom",
    description: "A double casement window with a fixed rectangular transom at the top",
    minWidth: 800,
    maxWidth: 2000,
    minHeight: 800,
    maxHeight: 2000,
    category: "window",
  },
  {
    id: "triple-transom",
    name: "Triple with Transom",
    description: "A triple casement window with a fixed rectangular transom at the top",
    minWidth: 1200,
    maxWidth: 2500,
    minHeight: 800,
    maxHeight: 2000,
    category: "window",
  },
  {
    id: "quad-transom",
    name: "Quad with Transom",
    description: "A quad casement window with a fixed rectangular transom at the top",
    minWidth: 1600,
    maxWidth: 3000,
    minHeight: 800,
    maxHeight: 2000,
    category: "window",
  },
  
  {
    id: "patio",
    name: "Patio Doors",
    description: "Large glass doors for patio access",
    minWidth: 1500,
    maxWidth: 3000,
    minHeight: 2000,
    maxHeight: 2500,
    category: "window",
  },
  
  // Door types
  {
    id: "door-fully-boarded",
    name: "Fully Boarded Door",
    description: "A traditional door with no glass panels",
    minWidth: 700,
    maxWidth: 1000,
    minHeight: 1800,
    maxHeight: 2400,
    category: "door",
    defaultWidth: 900,
    defaultHeight: 2100,
  },
  {
    id: "door-full-glazed",
    name: "Full Glazed Door",
    description: "A door with a large glass panel covering most of the door",
    minWidth: 700,
    maxWidth: 1000,
    minHeight: 1800,
    maxHeight: 2400,
    category: "door",
    defaultWidth: 900,
    defaultHeight: 2100,
  },
  {
    id: "door-half-glazed",
    name: "Half Glazed Door",
    description: "A door with the upper half containing a glass panel",
    minWidth: 700,
    maxWidth: 1000,
    minHeight: 1800,
    maxHeight: 2400,
    category: "door",
    defaultWidth: 900,
    defaultHeight: 2100,
  },
  {
    id: "door-6-panel",
    name: "6 Panel Door",
    description: "A classic door design with six panels",
    minWidth: 700,
    maxWidth: 1000,
    minHeight: 1800,
    maxHeight: 2400,
    category: "door",
    defaultWidth: 900,
    defaultHeight: 2100,
  }
];

// Get window type by ID
export function getWindowTypeById(id: string) {
  return windowTypes.find(type => type.id === id) || windowTypes[0];
}
